### ISSUE TITLE
Styling of bookdown

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/ta-manual#2]
I recommend using `bs4_book()`, so put the following in `output.yml`:

```
bookdown::bs4_book:
  theme:
    primary: "#00539B"
  repo: https://github.com/DukeStatSci/ta-manual
```

Instead of git_book

Happy to answer any questions about this!

See https://github.com/OpenIntroStat/ims/blob/master/_output.yml#L1-L8 as an example, but there's more there than you need!
